- name: Install LAMP Stack
  hosts: web
  become: yes
  tasks:
    - name: Update APT
      apt: update_cache=yes

    - name: Install Apache, MySQL, PHP
      apt: name={{ item }} state=present
      loop:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - unzip
